### ISSUE TITLE
api 키 발급 및 관리 이슈

### ISSUE THREAD

**Issue by Limchansol** [wafflestudio/csereal-web#27]
- 현재 카카오맵 api 키를 개인 이름으로 발급 받아 사용 중. 어떻게 처리할지 논의 필요
- 환경변수로 넣어두었는데 배포버전에서도 접근 가능하도록 처리해야 함 

_Originally posted by @Yeolyi in https://github.com/wafflestudio/csereal-web/issues/25#issuecomment-1670167726_

**Comment by yeolyi** [comment]
배포버전에서 접근가능하게는 처리했고, api 키는 문서화해서 담당자 바뀌면 새로 발급받아야된다고 써놓으면 될까?

**Comment by Limchansol** [comment]
> 배포버전에서 접근가능하게는 처리했고, api 키는 문서화해서 담당자 바뀌면 새로 발급받아야된다고 써놓으면 될까?

좋습니다 땡큐땡큐

**Comment by yeolyi** [comment]
위 PR에서 해결해 close처리합니다.
